---
- :label: Everything
  :href: http://search.lib.umich.edu/everything
- :label: Catalog
  :href: http://search.lib.umich.edu/catalog
  :current: true
- :label: Articles
  :href: http://search.lib.umich.edu/articles
- :label: Databases
  :href: http://search.lib.umich.edu/databases
- :label: Online Journals
  :href: http://search.lib.umich.edu/onlinejournals
- :label: Guides and more
  :href: http://search.lib.umich.edu/guidesandmore
